export const cash_discount_group = {
  options: () => ["id", "name", "discount_percent", "terms"],
  get: () => [{"id": 1, "name": "5% Net 15", "discount_percent": 5.0, "terms": "Net 15 days"}],
  getOne: (id) => (Array.isArray([{"id": 1, "name": "5% Net 15", "discount_percent": 5.0, "terms": "Net 15 days"}]) && [{"id": 1, "name": "5% Net 15", "discount_percent": 5.0, "terms": "Net 15 days"}].length ? [{"id": 1, "name": "5% Net 15", "discount_percent": 5.0, "terms": "Net 15 days"}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: cash_discount_group

export async function options() {
  return {
  "entity": "cash_discount_group",
  "primary_key": "id",
  "fields": [
    {
      "name": "id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "discount_percent",
      "type": "float",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "name",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "terms",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 10,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
