export const customer = {
  options: () => ["id", "name", "address", "email", "phone", "salesperson_id", "credit_limit"],
  get: () => [{"id": 1, "name": "Big Retailer Inc", "phone": "9999999999"}],
  getOne: (id) => (Array.isArray([{"id": 1, "name": "Big Retailer Inc", "phone": "9999999999"}]) && [{"id": 1, "name": "Big Retailer Inc", "phone": "9999999999"}].length ? [{"id": 1, "name": "Big Retailer Inc", "phone": "9999999999"}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: customer

export async function options() {
  return {
  "entity": "customer",
  "primary_key": "id",
  "fields": [
    {
      "name": "id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "address",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "credit_limit",
      "type": "float",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "email",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "name",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "phone",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "salesperson_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "salesperson.id",
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 10,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
