export const inventory = {
  options: () => ["id", "item_id", "location_id", "quantity"],
  get: () => [{"id": 1, "item_id": 1, "location_id": 1, "quantity": 150}],
  getOne: (id) => (Array.isArray([{"id": 1, "item_id": 1, "location_id": 1, "quantity": 150}]) && [{"id": 1, "item_id": 1, "location_id": 1, "quantity": 150}].length ? [{"id": 1, "item_id": 1, "location_id": 1, "quantity": 150}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: inventory

export async function options() {
  return {
  "entity": "inventory",
  "primary_key": "id",
  "fields": [
    {
      "name": "id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "item_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "item.id",
      "default": null
    },
    {
      "name": "location_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "inventory_location.id",
      "default": null
    },
    {
      "name": "quantity",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 10,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
