export const invoice_item = {
  options: () => ["invoice_id", "item_id", "quantity", "price"],
  get: () => [{"invoice_id": 1, "item_id": 1, "quantity": 5, "price": 1.25}],
  getOne: (id) => (Array.isArray([{"invoice_id": 1, "item_id": 1, "quantity": 5, "price": 1.25}]) && [{"invoice_id": 1, "item_id": 1, "quantity": 5, "price": 1.25}].length ? [{"invoice_id": 1, "item_id": 1, "quantity": 5, "price": 1.25}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: invoice_item

export async function options() {
  return {
  "entity": "invoice_item",
  "primary_key": "invoice_id",
  "fields": [
    {
      "name": "invoice_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": "invoice.id",
      "default": null
    },
    {
      "name": "item_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": "item.id",
      "default": null
    },
    {
      "name": "price",
      "type": "float",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "quantity",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 20,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
