export const invoice = {
  options: () => ["id", "customer_id", "date", "status"],
  get: () => [{"id": 1, "customer_id": 1, "date": "2024-08-01T09:00:00", "status": "Draft"}],
  getOne: (id) => (Array.isArray([{"id": 1, "customer_id": 1, "date": "2024-08-01T09:00:00", "status": "Draft"}]) && [{"id": 1, "customer_id": 1, "date": "2024-08-01T09:00:00", "status": "Draft"}].length ? [{"id": 1, "customer_id": 1, "date": "2024-08-01T09:00:00", "status": "Draft"}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: invoice

export async function options() {
  return {
  "entity": "invoice",
  "primary_key": "id",
  "fields": [
    {
      "name": "id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "customer_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "customer.id",
      "default": null
    },
    {
      "name": "date",
      "type": "datetime",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "status",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 10,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
