export const item = {
  options: () => ["id", "item_code", "name", "category_id", "secondary_category_id", "vendor_id", "tax_group_id", "price_group_id", "cash_discount_group_id", "upc_code", "unit", "price", "description", "active"],
  get: () => [{"id": 1, "item_code": "COKE500", "name": "Coke 500ml", "price": 1.25}],
  getOne: (id) => (Array.isArray([{"id": 1, "item_code": "COKE500", "name": "Coke 500ml", "price": 1.25}]) && [{"id": 1, "item_code": "COKE500", "name": "Coke 500ml", "price": 1.25}].length ? [{"id": 1, "item_code": "COKE500", "name": "Coke 500ml", "price": 1.25}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: item

export async function options() {
  return {
  "entity": "item",
  "primary_key": "id",
  "fields": [
    {
      "name": "id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "active",
      "type": "bool",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": true
    },
    {
      "name": "cash_discount_group_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "cash_discount_group.id",
      "default": null
    },
    {
      "name": "category_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "item_category.id",
      "default": null
    },
    {
      "name": "description",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "item_code",
      "type": "str",
      "label": null,
      "required": true,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "name",
      "type": "str",
      "label": null,
      "required": true,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "price",
      "type": "float",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "price_group_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "price_group.id",
      "default": null
    },
    {
      "name": "secondary_category_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "secondary_category.id",
      "default": null
    },
    {
      "name": "tax_group_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "tax_group.id",
      "default": null
    },
    {
      "name": "unit",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "upc_code",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "vendor_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": "vendor.id",
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 10,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
