export const price_group = {
  options: () => ["id", "name", "markup_percent"],
  get: () => [{"id": 1, "name": "Retail Pricing", "markup_percent": 12.5}],
  getOne: (id) => (Array.isArray([{"id": 1, "name": "Retail Pricing", "markup_percent": 12.5}]) && [{"id": 1, "name": "Retail Pricing", "markup_percent": 12.5}].length ? [{"id": 1, "name": "Retail Pricing", "markup_percent": 12.5}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: price_group

export async function options() {
  return {
  "entity": "price_group",
  "primary_key": "id",
  "fields": [
    {
      "name": "id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "markup_percent",
      "type": "float",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "name",
      "type": "str",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 10,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
