export const purchase_order_item = {
  options: () => ["po_id", "item_id", "quantity", "unit_price"],
  get: () => [{"po_id": 1, "item_id": 1, "quantity": 100, "unit_price": 1.05}],
  getOne: (id) => (Array.isArray([{"po_id": 1, "item_id": 1, "quantity": 100, "unit_price": 1.05}]) && [{"po_id": 1, "item_id": 1, "quantity": 100, "unit_price": 1.05}].length ? [{"po_id": 1, "item_id": 1, "quantity": 100, "unit_price": 1.05}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: purchase_order_item

export async function options() {
  return {
  "entity": "purchase_order_item",
  "primary_key": "item_id",
  "fields": [
    {
      "name": "item_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": "item.id",
      "default": null
    },
    {
      "name": "po_id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": "purchase_order.id",
      "default": null
    },
    {
      "name": "quantity",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "unit_price",
      "type": "float",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 10,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
