export const state = {
  options: () => ["id", "name"],
  get: () => [{"id": 1, "name": "California"}, {"id": 2, "name": "Texas"}, {"id": 3, "name": "New York"}],
  getOne: (id) => (Array.isArray([{"id": 1, "name": "California"}, {"id": 2, "name": "Texas"}, {"id": 3, "name": "New York"}]) && [{"id": 1, "name": "California"}, {"id": 2, "name": "Texas"}, {"id": 3, "name": "New York"}].length ? [{"id": 1, "name": "California"}, {"id": 2, "name": "Texas"}, {"id": 3, "name": "New York"}][0] : {}),
  post: (payload) => ({ ...payload, id: Math.floor(Math.random() * 10000) }),
  update: (payload) => payload,
};
// Auto-generated by code_generator.py — per-entity mock options
// entity: state

export async function options() {
  return {
  "entity": "state",
  "primary_key": "id",
  "fields": [
    {
      "name": "id",
      "type": "int",
      "label": null,
      "required": false,
      "read_only": false,
      "nullable": true,
      "primary_key": true,
      "foreign_key": null,
      "default": null
    },
    {
      "name": "name",
      "type": "str",
      "label": null,
      "required": true,
      "read_only": false,
      "nullable": true,
      "primary_key": false,
      "foreign_key": null,
      "default": null
    }
  ],
  "admin": {
    "table": {
      "delete_confirmation": true,
      "inline_edit": false,
      "show_filters": true,
      "page_size": 10,
      "global_search": true,
      "column_search": false,
      "sortable": true,
      "sticky_header": false
    },
    "form": null,
    "list": null
  }
}
}
