entities_data = { 'cash_discount_group': { 'sample_data': [ { 'discount_percent': 2312.45,
                                              'id': 7904,
                                              'name': 'level',
                                              'terms': 'deep'},
                                            { 'discount_percent': 235.28,
                                              'id': 5778,
                                              'name': 'hundred',
                                              'terms': 'wait'},
                                            { 'discount_percent': 8447.24,
                                              'id': 790,
                                              'name': 'Mrs',
                                              'terms': 'form'},
                                            { 'discount_percent': 8653.29,
                                              'id': 5544,
                                              'name': 'economic',
                                              'terms': 'couple'},
                                            { 'discount_percent': 1413.25,
                                              'id': 3599,
                                              'name': 'language',
                                              'terms': 'work'}]},
  'customer': { 'sample_data': [ { 'address': 'let',
                                   'credit_limit': 6485.85,
                                   'email': 'camera',
                                   'id': 8244,
                                   'name': 'according',
                                   'phone': 'training',
                                   'salesperson_id': 5332},
                                 { 'address': 'everything',
                                   'credit_limit': 5637.41,
                                   'email': 'model',
                                   'id': 8747,
                                   'name': 'daughter',
                                   'phone': 'training',
                                   'salesperson_id': 2282},
                                 { 'address': 'issue',
                                   'credit_limit': 7141.07,
                                   'email': 'during',
                                   'id': 2750,
                                   'name': 'admit',
                                   'phone': 'no',
                                   'salesperson_id': 3603},
                                 { 'address': 'of',
                                   'credit_limit': 2539.59,
                                   'email': 'skill',
                                   'id': 996,
                                   'name': 'similar',
                                   'phone': 'sometimes',
                                   'salesperson_id': 7653},
                                 { 'address': 'huge',
                                   'credit_limit': 2391.63,
                                   'email': 'talk',
                                   'id': 4527,
                                   'name': 'go',
                                   'phone': 'foot',
                                   'salesperson_id': 1880}]},
  'inventory': { 'sample_data': [ { 'id': 5535,
                                    'item_id': 4296,
                                    'location_id': 5199,
                                    'quantity': 7375},
                                  { 'id': 7620,
                                    'item_id': 1588,
                                    'location_id': 1173,
                                    'quantity': 41},
                                  { 'id': 7714,
                                    'item_id': 3470,
                                    'location_id': 3365,
                                    'quantity': 6988},
                                  { 'id': 8595,
                                    'item_id': 8888,
                                    'location_id': 2748,
                                    'quantity': 4749},
                                  { 'id': 2499,
                                    'item_id': 3625,
                                    'location_id': 8458,
                                    'quantity': 2679}]},
  'inventory_location': { 'sample_data': [ { 'address': 'candidate',
                                             'id': 1565,
                                             'name': 'world'},
                                           { 'address': 'right',
                                             'id': 5892,
                                             'name': 'lose'},
                                           { 'address': 'they',
                                             'id': 3239,
                                             'name': 'size'},
                                           { 'address': 'degree',
                                             'id': 6710,
                                             'name': 'a'},
                                           { 'address': 'color',
                                             'id': 4308,
                                             'name': 'tell'}]},
  'invoice': { 'sample_data': [ { 'customer_id': 6104,
                                  'date': '2025-02-28T23:41:48.657492',
                                  'id': 8953,
                                  'status': 'available'},
                                { 'customer_id': 1446,
                                  'date': '2025-04-06T18:04:00.443992',
                                  'id': 3498,
                                  'status': 'political'},
                                { 'customer_id': 6220,
                                  'date': '2025-01-21T20:34:42.357679',
                                  'id': 3427,
                                  'status': 'language'},
                                { 'customer_id': 6583,
                                  'date': '2025-03-05T07:43:32.335685',
                                  'id': 552,
                                  'status': 'model'},
                                { 'customer_id': 480,
                                  'date': '2025-03-10T16:58:48.486517',
                                  'id': 9840,
                                  'status': 'life'}]},
  'invoice_item': { 'sample_data': [ { 'invoice_id': 921,
                                       'item_id': 6727,
                                       'price': 5608.54,
                                       'quantity': 2571},
                                     { 'invoice_id': 1087,
                                       'item_id': 7271,
                                       'price': 9780.28,
                                       'quantity': 7254},
                                     { 'invoice_id': 4642,
                                       'item_id': 116,
                                       'price': 3309.82,
                                       'quantity': 4174},
                                     { 'invoice_id': 8742,
                                       'item_id': 9258,
                                       'price': 7403.14,
                                       'quantity': 8125},
                                     { 'invoice_id': 2554,
                                       'item_id': 3628,
                                       'price': 4562.48,
                                       'quantity': 6138}]},
  'item': { 'sample_data': [ { 'active': False,
                               'cash_discount_group_id': 8216,
                               'category_id': 1295,
                               'description': 'card',
                               'id': 6066,
                               'item_code': 'reflect',
                               'name': 'either',
                               'price': 6025.4,
                               'price_group_id': 6825,
                               'secondary_category_id': 5715,
                               'tax_group_id': 6712,
                               'unit': 'arm',
                               'upc_code': 'card',
                               'vendor_id': 9766},
                             { 'active': False,
                               'cash_discount_group_id': 1257,
                               'category_id': 7210,
                               'description': 'act',
                               'id': 8058,
                               'item_code': 'read',
                               'name': 'what',
                               'price': 4655.45,
                               'price_group_id': 5960,
                               'secondary_category_id': 7472,
                               'tax_group_id': 5041,
                               'unit': 'change',
                               'upc_code': 'else',
                               'vendor_id': 7811},
                             { 'active': False,
                               'cash_discount_group_id': 1325,
                               'category_id': 5923,
                               'description': 'participant',
                               'id': 1463,
                               'item_code': 'customer',
                               'name': 'several',
                               'price': 5712.88,
                               'price_group_id': 994,
                               'secondary_category_id': 6498,
                               'tax_group_id': 9299,
                               'unit': 'early',
                               'upc_code': 'reveal',
                               'vendor_id': 9562},
                             { 'active': False,
                               'cash_discount_group_id': 5873,
                               'category_id': 629,
                               'description': 'out',
                               'id': 7216,
                               'item_code': 'benefit',
                               'name': 'agree',
                               'price': 5922.47,
                               'price_group_id': 9394,
                               'secondary_category_id': 8619,
                               'tax_group_id': 1125,
                               'unit': 'budget',
                               'upc_code': 'culture',
                               'vendor_id': 9152},
                             { 'active': False,
                               'cash_discount_group_id': 8970,
                               'category_id': 7179,
                               'description': 'difficult',
                               'id': 8710,
                               'item_code': 'economy',
                               'name': 'be',
                               'price': 5849.1,
                               'price_group_id': 4028,
                               'secondary_category_id': 9434,
                               'tax_group_id': 8115,
                               'unit': 'hundred',
                               'upc_code': 'say',
                               'vendor_id': 4732}]},
  'item_category': { 'sample_data': [ { 'description': 'road',
                                        'id': 9179,
                                        'name': 'address'},
                                      { 'description': 'price',
                                        'id': 408,
                                        'name': 'kind'},
                                      { 'description': 'whom',
                                        'id': 7452,
                                        'name': 'nation'},
                                      { 'description': 'head',
                                        'id': 843,
                                        'name': 'treat'},
                                      { 'description': 'debate',
                                        'id': 5215,
                                        'name': 'later'}]},
  'price_group': { 'sample_data': [ { 'id': 3470,
                                      'markup_percent': 9267.63,
                                      'name': 'act'},
                                    { 'id': 7978,
                                      'markup_percent': 584.85,
                                      'name': 'not'},
                                    { 'id': 8018,
                                      'markup_percent': 7078.14,
                                      'name': 'race'},
                                    { 'id': 9456,
                                      'markup_percent': 2182.01,
                                      'name': 'commercial'},
                                    { 'id': 2373,
                                      'markup_percent': 2252.12,
                                      'name': 'much'}]},
  'purchase_order': { 'sample_data': [ { 'date': '2025-06-10T06:53:51.143644',
                                         'id': 565,
                                         'status': 'truth',
                                         'vendor_id': 6551},
                                       { 'date': '2025-05-30T14:02:56.892451',
                                         'id': 810,
                                         'status': 'never',
                                         'vendor_id': 6314},
                                       { 'date': '2025-06-12T11:29:39.853804',
                                         'id': 8444,
                                         'status': 'low',
                                         'vendor_id': 9448},
                                       { 'date': '2025-04-23T22:32:17.882050',
                                         'id': 8239,
                                         'status': 'animal',
                                         'vendor_id': 3336},
                                       { 'date': '2025-02-13T00:36:41.370967',
                                         'id': 1420,
                                         'status': 'either',
                                         'vendor_id': 8137}]},
  'purchase_order_item': { 'sample_data': [ { 'item_id': 8064,
                                              'po_id': 5051,
                                              'quantity': 844,
                                              'unit_price': 7975.04},
                                            { 'item_id': 3282,
                                              'po_id': 751,
                                              'quantity': 2391,
                                              'unit_price': 2900.87},
                                            { 'item_id': 143,
                                              'po_id': 7965,
                                              'quantity': 6597,
                                              'unit_price': 3888.76},
                                            { 'item_id': 5012,
                                              'po_id': 3114,
                                              'quantity': 933,
                                              'unit_price': 8220.45},
                                            { 'item_id': 9697,
                                              'po_id': 6311,
                                              'quantity': 3018,
                                              'unit_price': 8802.06}]},
  'salesperson': { 'sample_data': [ { 'email': 'size',
                                      'id': 3777,
                                      'name': 'follow',
                                      'phone': 'what'},
                                    { 'email': 'who',
                                      'id': 8743,
                                      'name': 'feel',
                                      'phone': 'program'},
                                    { 'email': 'maintain',
                                      'id': 273,
                                      'name': 'entire',
                                      'phone': 'field'},
                                    { 'email': 'bank',
                                      'id': 495,
                                      'name': 'wear',
                                      'phone': 'myself'},
                                    { 'email': 'lead',
                                      'id': 4494,
                                      'name': 'should',
                                      'phone': 'program'}]},
  'secondary_category': { 'sample_data': [ { 'description': 'night',
                                             'id': 6477,
                                             'name': 'effort'},
                                           { 'description': 'former',
                                             'id': 1834,
                                             'name': 'improve'},
                                           { 'description': 'great',
                                             'id': 3808,
                                             'name': 'example'},
                                           { 'description': 'employee',
                                             'id': 4526,
                                             'name': 'scene'},
                                           { 'description': 'health',
                                             'id': 5546,
                                             'name': 'product'}]},
  'tax_group': { 'sample_data': [ { 'id': 735,
                                    'name': 'win',
                                    'tax_percent': 8669.77},
                                  { 'id': 4120,
                                    'name': 'free',
                                    'tax_percent': 1269.6},
                                  { 'id': 4139,
                                    'name': 'break',
                                    'tax_percent': 3417.1},
                                  { 'id': 5524,
                                    'name': 'before',
                                    'tax_percent': 951.8},
                                  { 'id': 5663,
                                    'name': 'past',
                                    'tax_percent': 4332.79}]},
  'vendor': { 'sample_data': [ { 'address': 'message',
                                 'contact_person': 'but',
                                 'email': 'material',
                                 'id': 1180,
                                 'name': 'chance',
                                 'phone': 'you'},
                               { 'address': 'bank',
                                 'contact_person': 'rise',
                                 'email': 'reflect',
                                 'id': 3185,
                                 'name': 'share',
                                 'phone': 'party'},
                               { 'address': 'pass',
                                 'contact_person': 'strategy',
                                 'email': 'first',
                                 'id': 4520,
                                 'name': 'indicate',
                                 'phone': 'agree'},
                               { 'address': 'affect',
                                 'contact_person': 'hair',
                                 'email': 'up',
                                 'id': 205,
                                 'name': 'than',
                                 'phone': 'technology'},
                               { 'address': 'toward',
                                 'contact_person': 'speech',
                                 'email': 'dream',
                                 'id': 7416,
                                 'name': 'a',
                                 'phone': 'paper'}]}}