entities_data = { 'cash_discount_group': { 'sample_data': [ { 'discount_percent': 6001.89,
                                              'id': 7396,
                                              'name': 'everybody',
                                              'terms': 'last'},
                                            { 'discount_percent': 2412.37,
                                              'id': 1567,
                                              'name': 'identify',
                                              'terms': 'talk'},
                                            { 'discount_percent': 2522.64,
                                              'id': 2483,
                                              'name': 'market',
                                              'terms': 'central'},
                                            { 'discount_percent': 3623.68,
                                              'id': 1885,
                                              'name': 'mission',
                                              'terms': 'push'},
                                            { 'discount_percent': 8165.44,
                                              'id': 2279,
                                              'name': 'service',
                                              'terms': 'consumer'}]},
  'customer': { 'sample_data': [ { 'address': 'single',
                                   'credit_limit': 6292.36,
                                   'email': 'even',
                                   'id': 5100,
                                   'name': 'manage',
                                   'phone': 'bill',
                                   'salesperson_id': 8039},
                                 { 'address': 'truth',
                                   'credit_limit': 7805.02,
                                   'email': 'leave',
                                   'id': 9402,
                                   'name': 'each',
                                   'phone': 'require',
                                   'salesperson_id': 9638},
                                 { 'address': 'report',
                                   'credit_limit': 8012.47,
                                   'email': 'top',
                                   'id': 1895,
                                   'name': 'argue',
                                   'phone': 'address',
                                   'salesperson_id': 7488},
                                 { 'address': 'hotel',
                                   'credit_limit': 247.24,
                                   'email': 'late',
                                   'id': 2289,
                                   'name': 'year',
                                   'phone': 'fund',
                                   'salesperson_id': 4674},
                                 { 'address': 'seven',
                                   'credit_limit': 2447.88,
                                   'email': 'man',
                                   'id': 3494,
                                   'name': 'usually',
                                   'phone': 'whether',
                                   'salesperson_id': 2723}]},
  'inventory': { 'sample_data': [ { 'id': 2283,
                                    'item_id': 4362,
                                    'location_id': 4385,
                                    'quantity': 6660},
                                  { 'id': 6205,
                                    'item_id': 736,
                                    'location_id': 981,
                                    'quantity': 4733},
                                  { 'id': 7555,
                                    'item_id': 3577,
                                    'location_id': 107,
                                    'quantity': 6011},
                                  { 'id': 4836,
                                    'item_id': 8289,
                                    'location_id': 5572,
                                    'quantity': 6579},
                                  { 'id': 115,
                                    'item_id': 9191,
                                    'location_id': 8486,
                                    'quantity': 1965}]},
  'inventory_location': { 'sample_data': [ { 'address': 'teacher',
                                             'id': 3646,
                                             'name': 'seven'},
                                           { 'address': 'project',
                                             'id': 340,
                                             'name': 'store'},
                                           { 'address': 'send',
                                             'id': 6174,
                                             'name': 'energy'},
                                           { 'address': 'product',
                                             'id': 3078,
                                             'name': 'sort'},
                                           { 'address': 'pick',
                                             'id': 4500,
                                             'name': 'keep'}]},
  'invoice': { 'sample_data': [ { 'customer_id': 8549,
                                  'date': None,
                                  'id': 278,
                                  'status': 'language'},
                                { 'customer_id': 1206,
                                  'date': None,
                                  'id': 7976,
                                  'status': 'interesting'},
                                { 'customer_id': 1516,
                                  'date': None,
                                  'id': 191,
                                  'status': 'executive'},
                                { 'customer_id': 3606,
                                  'date': None,
                                  'id': 4606,
                                  'status': 'eat'},
                                { 'customer_id': 1587,
                                  'date': None,
                                  'id': 6455,
                                  'status': 'serious'}]},
  'invoice_item': { 'sample_data': [ { 'invoice_id': 1396,
                                       'item_id': 8243,
                                       'price': 4566.21,
                                       'quantity': 2713},
                                     { 'invoice_id': 1893,
                                       'item_id': 463,
                                       'price': 80.4,
                                       'quantity': 6224},
                                     { 'invoice_id': 9576,
                                       'item_id': 1106,
                                       'price': 5586.99,
                                       'quantity': 1587},
                                     { 'invoice_id': 582,
                                       'item_id': 5729,
                                       'price': 119.89,
                                       'quantity': 5395},
                                     { 'invoice_id': 5708,
                                       'item_id': 1257,
                                       'price': 4990.3,
                                       'quantity': 3817}]},
  'item': { 'sample_data': [ { 'active': False,
                               'cash_discount_group_id': 8013,
                               'category_id': 2884,
                               'description': 'increase',
                               'id': 5559,
                               'item_code': 'each',
                               'name': 'only',
                               'price': 2046.71,
                               'price_group_id': 6962,
                               'secondary_category_id': 6398,
                               'tax_group_id': 7961,
                               'unit': 'history',
                               'upc_code': 'interesting',
                               'vendor_id': 6100},
                             { 'active': False,
                               'cash_discount_group_id': 9444,
                               'category_id': 1614,
                               'description': 'listen',
                               'id': 6413,
                               'item_code': 'maintain',
                               'name': 'unit',
                               'price': 234.25,
                               'price_group_id': 5248,
                               'secondary_category_id': 4137,
                               'tax_group_id': 2599,
                               'unit': 'art',
                               'upc_code': 'pull',
                               'vendor_id': 3826},
                             { 'active': True,
                               'cash_discount_group_id': 1716,
                               'category_id': 7821,
                               'description': 'similar',
                               'id': 6605,
                               'item_code': 'adult',
                               'name': 'figure',
                               'price': 8890.97,
                               'price_group_id': 1022,
                               'secondary_category_id': 3534,
                               'tax_group_id': 7301,
                               'unit': 'son',
                               'upc_code': 'model',
                               'vendor_id': 3878},
                             { 'active': False,
                               'cash_discount_group_id': 8064,
                               'category_id': 7229,
                               'description': 'mention',
                               'id': 8081,
                               'item_code': 'who',
                               'name': 'stand',
                               'price': 7993.91,
                               'price_group_id': 6625,
                               'secondary_category_id': 3550,
                               'tax_group_id': 60,
                               'unit': 'ball',
                               'upc_code': 'free',
                               'vendor_id': 2464},
                             { 'active': True,
                               'cash_discount_group_id': 65,
                               'category_id': 3211,
                               'description': 'half',
                               'id': 5114,
                               'item_code': 'message',
                               'name': 'point',
                               'price': 3044.1,
                               'price_group_id': 2536,
                               'secondary_category_id': 5788,
                               'tax_group_id': 1985,
                               'unit': 'everybody',
                               'upc_code': 'politics',
                               'vendor_id': 2360}]},
  'item_category': { 'sample_data': [ { 'description': 'important',
                                        'id': 6839,
                                        'name': 'throw'},
                                      { 'description': 'suffer',
                                        'id': 2986,
                                        'name': 'answer'},
                                      { 'description': 'deal',
                                        'id': 1662,
                                        'name': 'everyone'},
                                      { 'description': 'ability',
                                        'id': 4241,
                                        'name': 'while'},
                                      { 'description': 'security',
                                        'id': 2515,
                                        'name': 'hundred'}]},
  'price_group': { 'sample_data': [ { 'id': 9372,
                                      'markup_percent': 6831.0,
                                      'name': 'business'},
                                    { 'id': 9890,
                                      'markup_percent': 3842.41,
                                      'name': 'nor'},
                                    { 'id': 796,
                                      'markup_percent': 4277.25,
                                      'name': 'station'},
                                    { 'id': 6930,
                                      'markup_percent': 2664.42,
                                      'name': 'who'},
                                    { 'id': 4603,
                                      'markup_percent': 7114.97,
                                      'name': 'difficult'}]},
  'purchase_order': { 'sample_data': [ { 'date': None,
                                         'id': 3873,
                                         'status': 'bad',
                                         'vendor_id': 2924},
                                       { 'date': None,
                                         'id': 2140,
                                         'status': 'eat',
                                         'vendor_id': 8606},
                                       { 'date': None,
                                         'id': 3253,
                                         'status': 'always',
                                         'vendor_id': 5754},
                                       { 'date': None,
                                         'id': 8516,
                                         'status': 'just',
                                         'vendor_id': 2952},
                                       { 'date': None,
                                         'id': 7633,
                                         'status': 'pattern',
                                         'vendor_id': 9469}]},
  'purchase_order_item': { 'sample_data': [ { 'item_id': 5797,
                                              'po_id': 7740,
                                              'quantity': 7925,
                                              'unit_price': 8681.2},
                                            { 'item_id': 3953,
                                              'po_id': 4556,
                                              'quantity': 7326,
                                              'unit_price': 6349.98},
                                            { 'item_id': 9221,
                                              'po_id': 4350,
                                              'quantity': 5320,
                                              'unit_price': 4938.4},
                                            { 'item_id': 9354,
                                              'po_id': 9173,
                                              'quantity': 2831,
                                              'unit_price': 9415.01},
                                            { 'item_id': 6612,
                                              'po_id': 611,
                                              'quantity': 1256,
                                              'unit_price': 6112.9}]},
  'salesperson': { 'sample_data': [ { 'email': 'degree',
                                      'id': 5753,
                                      'name': 'job',
                                      'phone': 'continue'},
                                    { 'email': 'energy',
                                      'id': 4392,
                                      'name': 'listen',
                                      'phone': 'parent'},
                                    { 'email': 'green',
                                      'id': 1378,
                                      'name': 'recently',
                                      'phone': 'doctor'},
                                    { 'email': 'everybody',
                                      'id': 8678,
                                      'name': 'wait',
                                      'phone': 'along'},
                                    { 'email': 'above',
                                      'id': 6897,
                                      'name': 'officer',
                                      'phone': 'at'}]},
  'secondary_category': { 'sample_data': [ { 'description': 'score',
                                             'id': 1969,
                                             'name': 'oil'},
                                           { 'description': 'hard',
                                             'id': 8876,
                                             'name': 'after'},
                                           { 'description': 'he',
                                             'id': 4691,
                                             'name': 'black'},
                                           { 'description': 'area',
                                             'id': 3198,
                                             'name': 'radio'},
                                           { 'description': 'discussion',
                                             'id': 4300,
                                             'name': 'wish'}]},
  'tax_group': { 'sample_data': [ { 'id': 6891,
                                    'name': 'far',
                                    'tax_percent': 1671.97},
                                  { 'id': 6441,
                                    'name': 'result',
                                    'tax_percent': 292.2},
                                  { 'id': 2357,
                                    'name': 'however',
                                    'tax_percent': 9159.24},
                                  { 'id': 6221,
                                    'name': 'great',
                                    'tax_percent': 9661.1},
                                  { 'id': 6924,
                                    'name': 'either',
                                    'tax_percent': 870.0}]},
  'vendor': { 'sample_data': [ { 'address': 'tonight',
                                 'contact_person': 'card',
                                 'email': 'look',
                                 'id': 1076,
                                 'name': 'response',
                                 'phone': 'president'},
                               { 'address': 'southern',
                                 'contact_person': 'attorney',
                                 'email': 'change',
                                 'id': 1300,
                                 'name': 'participant',
                                 'phone': 'least'},
                               { 'address': 'lay',
                                 'contact_person': 'moment',
                                 'email': 'section',
                                 'id': 8174,
                                 'name': 'want',
                                 'phone': 'manage'},
                               { 'address': 'save',
                                 'contact_person': 'light',
                                 'email': 'despite',
                                 'id': 7886,
                                 'name': 'mouth',
                                 'phone': 'clear'},
                               { 'address': 'development',
                                 'contact_person': 'often',
                                 'email': 'different',
                                 'id': 290,
                                 'name': 'safe',
                                 'phone': 'rock'}]}}