entities_data = { 'cash_discount_group': { 'sample_data': [ { 'discount_percent': 7821.5,
                                              'id': 4991,
                                              'name': 'stuff',
                                              'terms': 'beautiful'},
                                            { 'discount_percent': 4332.72,
                                              'id': 9121,
                                              'name': 'chance',
                                              'terms': 'may'},
                                            { 'discount_percent': 5289.01,
                                              'id': 7107,
                                              'name': 'stand',
                                              'terms': 'site'},
                                            { 'discount_percent': 8340.61,
                                              'id': 5704,
                                              'name': 'difficult',
                                              'terms': 'not'},
                                            { 'discount_percent': 7070.99,
                                              'id': 4115,
                                              'name': 'decide',
                                              'terms': 'inside'}]},
  'customer': { 'sample_data': [ { 'address': 'wide',
                                   'credit_limit': 3390.73,
                                   'email': 'production',
                                   'id': 2796,
                                   'name': 'three',
                                   'phone': 'today',
                                   'salesperson_id': 8638},
                                 { 'address': 'opportunity',
                                   'credit_limit': 1985.36,
                                   'email': 'force',
                                   'id': 4429,
                                   'name': 'fine',
                                   'phone': 'go',
                                   'salesperson_id': 194},
                                 { 'address': 'parent',
                                   'credit_limit': 1994.27,
                                   'email': 'science',
                                   'id': 8302,
                                   'name': 'result',
                                   'phone': 'green',
                                   'salesperson_id': 6312},
                                 { 'address': 'machine',
                                   'credit_limit': 5868.97,
                                   'email': 'meet',
                                   'id': 9385,
                                   'name': 'vote',
                                   'phone': 'still',
                                   'salesperson_id': 103},
                                 { 'address': 'generation',
                                   'credit_limit': 8251.43,
                                   'email': 'people',
                                   'id': 5593,
                                   'name': 'determine',
                                   'phone': 'here',
                                   'salesperson_id': 6860}]},
  'inventory': { 'sample_data': [ { 'id': 8084,
                                    'item_id': 7647,
                                    'location_id': 9957,
                                    'quantity': 7738},
                                  { 'id': 6002,
                                    'item_id': 4202,
                                    'location_id': 5232,
                                    'quantity': 9357},
                                  { 'id': 1482,
                                    'item_id': 6168,
                                    'location_id': 1822,
                                    'quantity': 8373},
                                  { 'id': 8594,
                                    'item_id': 7755,
                                    'location_id': 2533,
                                    'quantity': 5710},
                                  { 'id': 2804,
                                    'item_id': 5631,
                                    'location_id': 7102,
                                    'quantity': 4749}]},
  'inventory_location': { 'sample_data': [ { 'address': 'baby',
                                             'id': 5631,
                                             'name': 'station'},
                                           { 'address': 'sound',
                                             'id': 9818,
                                             'name': 'learn'},
                                           { 'address': 'tough',
                                             'id': 3720,
                                             'name': 'enter'},
                                           { 'address': 'trade',
                                             'id': 260,
                                             'name': 'like'},
                                           { 'address': 'once',
                                             'id': 9103,
                                             'name': 'feel'}]},
  'invoice': { 'sample_data': [ { 'customer_id': 8195,
                                  'date': None,
                                  'id': 6679,
                                  'status': 'various'},
                                { 'customer_id': 3945,
                                  'date': None,
                                  'id': 9731,
                                  'status': 'say'},
                                { 'customer_id': 4300,
                                  'date': None,
                                  'id': 1459,
                                  'status': 'color'},
                                { 'customer_id': 4583,
                                  'date': None,
                                  'id': 5261,
                                  'status': 'charge'},
                                { 'customer_id': 4297,
                                  'date': None,
                                  'id': 3277,
                                  'status': 'daughter'}]},
  'invoice_item': { 'sample_data': [ { 'invoice_id': 9450,
                                       'item_id': 3294,
                                       'price': 5865.34,
                                       'quantity': 116},
                                     { 'invoice_id': 7152,
                                       'item_id': 4066,
                                       'price': 1097.74,
                                       'quantity': 8818},
                                     { 'invoice_id': 5836,
                                       'item_id': 1716,
                                       'price': 8269.87,
                                       'quantity': 3968},
                                     { 'invoice_id': 2975,
                                       'item_id': 9680,
                                       'price': 8725.25,
                                       'quantity': 6369},
                                     { 'invoice_id': 6269,
                                       'item_id': 8134,
                                       'price': 8361.89,
                                       'quantity': 5981}]},
  'item': { 'sample_data': [ { 'active': True,
                               'cash_discount_group_id': 161,
                               'category_id': 5154,
                               'description': 'dog',
                               'id': 3164,
                               'item_code': 'arrive',
                               'name': 'since',
                               'price': 3081.61,
                               'price_group_id': 226,
                               'secondary_category_id': 9421,
                               'tax_group_id': 9953,
                               'unit': 'Democrat',
                               'upc_code': 'play',
                               'vendor_id': 8117},
                             { 'active': False,
                               'cash_discount_group_id': 3800,
                               'category_id': 8026,
                               'description': 'before',
                               'id': 1512,
                               'item_code': 'suffer',
                               'name': 'society',
                               'price': 2057.78,
                               'price_group_id': 9267,
                               'secondary_category_id': 2296,
                               'tax_group_id': 8574,
                               'unit': 'industry',
                               'upc_code': 'red',
                               'vendor_id': 8879},
                             { 'active': True,
                               'cash_discount_group_id': 9243,
                               'category_id': 3125,
                               'description': 'couple',
                               'id': 7763,
                               'item_code': 'process',
                               'name': 'interview',
                               'price': 791.9,
                               'price_group_id': 7722,
                               'secondary_category_id': 8928,
                               'tax_group_id': 6947,
                               'unit': 'term',
                               'upc_code': 'sit',
                               'vendor_id': 8627},
                             { 'active': True,
                               'cash_discount_group_id': 1572,
                               'category_id': 2646,
                               'description': 'our',
                               'id': 9589,
                               'item_code': 'while',
                               'name': 'boy',
                               'price': 9884.89,
                               'price_group_id': 8552,
                               'secondary_category_id': 2826,
                               'tax_group_id': 2816,
                               'unit': 'nation',
                               'upc_code': 'theory',
                               'vendor_id': 3650},
                             { 'active': False,
                               'cash_discount_group_id': 6410,
                               'category_id': 7786,
                               'description': 'number',
                               'id': 4411,
                               'item_code': 'home',
                               'name': 'behavior',
                               'price': 7565.66,
                               'price_group_id': 8229,
                               'secondary_category_id': 1109,
                               'tax_group_id': 8316,
                               'unit': 'area',
                               'upc_code': 'shake',
                               'vendor_id': 58}]},
  'item_category': { 'sample_data': [ { 'description': 'know',
                                        'id': 4779,
                                        'name': 'miss'},
                                      { 'description': 'know',
                                        'id': 4263,
                                        'name': 'later'},
                                      { 'description': 'sell',
                                        'id': 2079,
                                        'name': 'bag'},
                                      { 'description': 'type',
                                        'id': 2049,
                                        'name': 'how'},
                                      { 'description': 'investment',
                                        'id': 8960,
                                        'name': 'fill'}]},
  'price_group': { 'sample_data': [ { 'id': 9908,
                                      'markup_percent': 1444.61,
                                      'name': 'family'},
                                    { 'id': 5286,
                                      'markup_percent': 1644.35,
                                      'name': 'say'},
                                    { 'id': 2836,
                                      'markup_percent': 5877.73,
                                      'name': 'across'},
                                    { 'id': 517,
                                      'markup_percent': 9731.7,
                                      'name': 'partner'},
                                    { 'id': 3111,
                                      'markup_percent': 8998.15,
                                      'name': 'second'}]},
  'purchase_order': { 'sample_data': [ { 'date': None,
                                         'id': 2583,
                                         'status': 'media',
                                         'vendor_id': 6443},
                                       { 'date': None,
                                         'id': 7021,
                                         'status': 'already',
                                         'vendor_id': 7982},
                                       { 'date': None,
                                         'id': 4968,
                                         'status': 'live',
                                         'vendor_id': 8501},
                                       { 'date': None,
                                         'id': 3939,
                                         'status': 'part',
                                         'vendor_id': 4266},
                                       { 'date': None,
                                         'id': 9527,
                                         'status': 'newspaper',
                                         'vendor_id': 9148}]},
  'purchase_order_item': { 'sample_data': [ { 'item_id': 3911,
                                              'po_id': 3124,
                                              'quantity': 8981,
                                              'unit_price': 4598.54},
                                            { 'item_id': 8716,
                                              'po_id': 3157,
                                              'quantity': 7525,
                                              'unit_price': 3669.07},
                                            { 'item_id': 7296,
                                              'po_id': 7902,
                                              'quantity': 8217,
                                              'unit_price': 3856.45},
                                            { 'item_id': 8033,
                                              'po_id': 6504,
                                              'quantity': 6431,
                                              'unit_price': 490.49},
                                            { 'item_id': 3358,
                                              'po_id': 58,
                                              'quantity': 1989,
                                              'unit_price': 9852.61}]},
  'salesperson': { 'sample_data': [ { 'email': 'wonder',
                                      'id': 9194,
                                      'name': 'appear',
                                      'phone': 'manage'},
                                    { 'email': 'open',
                                      'id': 2125,
                                      'name': 'perhaps',
                                      'phone': 'month'},
                                    { 'email': 'here',
                                      'id': 4652,
                                      'name': 'laugh',
                                      'phone': 'recently'},
                                    { 'email': 'instead',
                                      'id': 4405,
                                      'name': 'none',
                                      'phone': 'check'},
                                    { 'email': 'reality',
                                      'id': 8523,
                                      'name': 'type',
                                      'phone': 'thank'}]},
  'secondary_category': { 'sample_data': [ { 'description': 'them',
                                             'id': 2378,
                                             'name': 'well'},
                                           { 'description': 'each',
                                             'id': 8837,
                                             'name': 'environmental'},
                                           { 'description': 'open',
                                             'id': 2978,
                                             'name': 'property'},
                                           { 'description': 'data',
                                             'id': 2170,
                                             'name': 'religious'},
                                           { 'description': 'plan',
                                             'id': 5241,
                                             'name': 'open'}]},
  'tax_group': { 'sample_data': [ { 'id': 562,
                                    'name': 'certainly',
                                    'tax_percent': 17.53},
                                  { 'id': 1615,
                                    'name': 'suggest',
                                    'tax_percent': 2322.2},
                                  { 'id': 7029,
                                    'name': 'answer',
                                    'tax_percent': 324.33},
                                  { 'id': 6317,
                                    'name': 'environmental',
                                    'tax_percent': 2731.95},
                                  { 'id': 6251,
                                    'name': 'spring',
                                    'tax_percent': 9041.25}]},
  'vendor': { 'sample_data': [ { 'address': 'such',
                                 'contact_person': 'field',
                                 'email': 'thing',
                                 'id': 2607,
                                 'name': 'provide',
                                 'phone': 'condition'},
                               { 'address': 'religious',
                                 'contact_person': 'task',
                                 'email': 'sure',
                                 'id': 4167,
                                 'name': 'thus',
                                 'phone': 'nearly'},
                               { 'address': 'TV',
                                 'contact_person': 'hard',
                                 'email': 'future',
                                 'id': 1079,
                                 'name': 'position',
                                 'phone': 'owner'},
                               { 'address': 'arm',
                                 'contact_person': 'yeah',
                                 'email': 'up',
                                 'id': 1695,
                                 'name': 'public',
                                 'phone': 'ahead'},
                               { 'address': 'left',
                                 'contact_person': 'choice',
                                 'email': 'political',
                                 'id': 5735,
                                 'name': 'affect',
                                 'phone': 'consider'}]}}