# AUTO-GENERATED for pioneer_wholesale_inc. Do not edit by hand.
# Source: clients/pioneer_wholesale_inc/entities.py
# Seed: 1337

import datetime

sample_data = {'cash_discount_group': [{'discount_percent': 100.0, 'id': 1, 'name': 'name_0', 'terms': 'terms_0'},
                         {'discount_percent': 101.1, 'id': 2, 'name': 'name_1', 'terms': 'terms_1'},
                         {'discount_percent': 102.2, 'id': 3, 'name': 'name_2', 'terms': 'terms_2'},
                         {'discount_percent': 103.3, 'id': 4, 'name': 'name_3', 'terms': 'terms_3'},
                         {'discount_percent': 104.4,
                          'id': 5,
                          'name': 'name_4',
                          'terms': 'terms_4'}],
 'customer': [{'address': 'address_0',
               'credit_limit': 100.0,
               'email': 'email_0',
               'id': 1,
               'name': 'name_0',
               'phone': 'phone_0',
               'salesperson_id': 1},
              {'address': 'address_1',
               'credit_limit': 101.1,
               'email': 'email_1',
               'id': 2,
               'name': 'name_1',
               'phone': 'phone_1',
               'salesperson_id': 2},
              {'address': 'address_2',
               'credit_limit': 102.2,
               'email': 'email_2',
               'id': 3,
               'name': 'name_2',
               'phone': 'phone_2',
               'salesperson_id': 3},
              {'address': 'address_3',
               'credit_limit': 103.3,
               'email': 'email_3',
               'id': 4,
               'name': 'name_3',
               'phone': 'phone_3',
               'salesperson_id': 4},
              {'address': 'address_4',
               'credit_limit': 104.4,
               'email': 'email_4',
               'id': 5,
               'name': 'name_4',
               'phone': 'phone_4',
               'salesperson_id': 5}],
 'inventory': [{'id': 1, 'item_id': 1, 'location_id': 1, 'quantity': 1},
               {'id': 2, 'item_id': 2, 'location_id': 2, 'quantity': 2},
               {'id': 3, 'item_id': 3, 'location_id': 3, 'quantity': 3},
               {'id': 4, 'item_id': 4, 'location_id': 4, 'quantity': 4},
               {'id': 5, 'item_id': 5, 'location_id': 5, 'quantity': 5}],
 'inventory_location': [{'address': 'address_0', 'id': 1, 'name': 'name_0'},
                        {'address': 'address_1', 'id': 2, 'name': 'name_1'},
                        {'address': 'address_2', 'id': 3, 'name': 'name_2'},
                        {'address': 'address_3', 'id': 4, 'name': 'name_3'},
                        {'address': 'address_4', 'id': 5, 'name': 'name_4'}],
 'invoice': [{'customer_id': 1, 'date': datetime.date(2025, 1, 1), 'id': 1, 'status': 'status_0'},
             {'customer_id': 2, 'date': datetime.date(2025, 1, 2), 'id': 2, 'status': 'status_1'},
             {'customer_id': 3, 'date': datetime.date(2025, 1, 3), 'id': 3, 'status': 'status_2'},
             {'customer_id': 4, 'date': datetime.date(2025, 1, 4), 'id': 4, 'status': 'status_3'},
             {'customer_id': 5, 'date': datetime.date(2025, 1, 5), 'id': 5, 'status': 'status_4'}],
 'invoice_item': [{'invoice_id': 1, 'item_id': 1, 'price': 100.0, 'quantity': 1},
                  {'invoice_id': 2, 'item_id': 2, 'price': 101.1, 'quantity': 2},
                  {'invoice_id': 3, 'item_id': 3, 'price': 102.2, 'quantity': 3},
                  {'invoice_id': 4, 'item_id': 4, 'price': 103.3, 'quantity': 4},
                  {'invoice_id': 5, 'item_id': 5, 'price': 104.4, 'quantity': 5}],
 'item': [{'active': True,
           'cash_discount_group_id': 1,
           'category_id': 1,
           'description': 'description_0',
           'id': 1,
           'item_code': 'item_code_0',
           'name': 'name_0',
           'price': 100.0,
           'price_group_id': 1,
           'secondary_category_id': 1,
           'tax_group_id': 1,
           'unit': 'unit_0',
           'upc_code': 'upc_code_0',
           'vendor_id': 1},
          {'active': False,
           'cash_discount_group_id': 2,
           'category_id': 2,
           'description': 'description_1',
           'id': 2,
           'item_code': 'item_code_1',
           'name': 'name_1',
           'price': 101.1,
           'price_group_id': 2,
           'secondary_category_id': 2,
           'tax_group_id': 2,
           'unit': 'unit_1',
           'upc_code': 'upc_code_1',
           'vendor_id': 2},
          {'active': True,
           'cash_discount_group_id': 3,
           'category_id': 3,
           'description': 'description_2',
           'id': 3,
           'item_code': 'item_code_2',
           'name': 'name_2',
           'price': 102.2,
           'price_group_id': 3,
           'secondary_category_id': 3,
           'tax_group_id': 3,
           'unit': 'unit_2',
           'upc_code': 'upc_code_2',
           'vendor_id': 3},
          {'active': False,
           'cash_discount_group_id': 4,
           'category_id': 4,
           'description': 'description_3',
           'id': 4,
           'item_code': 'item_code_3',
           'name': 'name_3',
           'price': 103.3,
           'price_group_id': 4,
           'secondary_category_id': 4,
           'tax_group_id': 4,
           'unit': 'unit_3',
           'upc_code': 'upc_code_3',
           'vendor_id': 4},
          {'active': True,
           'cash_discount_group_id': 5,
           'category_id': 5,
           'description': 'description_4',
           'id': 5,
           'item_code': 'item_code_4',
           'name': 'name_4',
           'price': 104.4,
           'price_group_id': 5,
           'secondary_category_id': 5,
           'tax_group_id': 5,
           'unit': 'unit_4',
           'upc_code': 'upc_code_4',
           'vendor_id': 5}],
 'item_category': [{'description': 'description_0', 'id': 1, 'name': 'name_0'},
                   {'description': 'description_1', 'id': 2, 'name': 'name_1'},
                   {'description': 'description_2', 'id': 3, 'name': 'name_2'},
                   {'description': 'description_3', 'id': 4, 'name': 'name_3'},
                   {'description': 'description_4', 'id': 5, 'name': 'name_4'}],
 'price_group': [{'id': 1, 'markup_percent': 100.0, 'name': 'name_0'},
                 {'id': 2, 'markup_percent': 101.1, 'name': 'name_1'},
                 {'id': 3, 'markup_percent': 102.2, 'name': 'name_2'},
                 {'id': 4, 'markup_percent': 103.3, 'name': 'name_3'},
                 {'id': 5, 'markup_percent': 104.4, 'name': 'name_4'}],
 'purchase_order': [{'date': datetime.date(2025, 1, 1),
                     'id': 1,
                     'status': 'status_0',
                     'vendor_id': 1},
                    {'date': datetime.date(2025, 1, 2),
                     'id': 2,
                     'status': 'status_1',
                     'vendor_id': 2},
                    {'date': datetime.date(2025, 1, 3),
                     'id': 3,
                     'status': 'status_2',
                     'vendor_id': 3},
                    {'date': datetime.date(2025, 1, 4),
                     'id': 4,
                     'status': 'status_3',
                     'vendor_id': 4},
                    {'date': datetime.date(2025, 1, 5),
                     'id': 5,
                     'status': 'status_4',
                     'vendor_id': 5}],
 'purchase_order_item': [{'item_id': 1, 'po_id': 1, 'quantity': 1, 'unit_price': 100.0},
                         {'item_id': 2, 'po_id': 2, 'quantity': 2, 'unit_price': 101.1},
                         {'item_id': 3, 'po_id': 3, 'quantity': 3, 'unit_price': 102.2},
                         {'item_id': 4, 'po_id': 4, 'quantity': 4, 'unit_price': 103.3},
                         {'item_id': 5, 'po_id': 5, 'quantity': 5, 'unit_price': 104.4}],
 'salesperson': [{'email': 'email_0', 'id': 1, 'name': 'name_0', 'phone': 'phone_0'},
                 {'email': 'email_1', 'id': 2, 'name': 'name_1', 'phone': 'phone_1'},
                 {'email': 'email_2', 'id': 3, 'name': 'name_2', 'phone': 'phone_2'},
                 {'email': 'email_3', 'id': 4, 'name': 'name_3', 'phone': 'phone_3'},
                 {'email': 'email_4', 'id': 5, 'name': 'name_4', 'phone': 'phone_4'}],
 'secondary_category': [{'description': 'description_0', 'id': 1, 'name': 'name_0'},
                        {'description': 'description_1', 'id': 2, 'name': 'name_1'},
                        {'description': 'description_2', 'id': 3, 'name': 'name_2'},
                        {'description': 'description_3', 'id': 4, 'name': 'name_3'},
                        {'description': 'description_4', 'id': 5, 'name': 'name_4'}],
 'state': [{'id': 1, 'name': 'name_0'},
           {'id': 2, 'name': 'name_1'},
           {'id': 3, 'name': 'name_2'},
           {'id': 4, 'name': 'name_3'},
           {'id': 5, 'name': 'name_4'}],
 'tax_group': [{'id': 1, 'name': 'name_0', 'tax_percent': 100.0},
               {'id': 2, 'name': 'name_1', 'tax_percent': 101.1},
               {'id': 3, 'name': 'name_2', 'tax_percent': 102.2},
               {'id': 4, 'name': 'name_3', 'tax_percent': 103.3},
               {'id': 5, 'name': 'name_4', 'tax_percent': 104.4}],
 'vendor': [{'address': 'address_0',
             'contact_person': 'contact_person_0',
             'email': 'email_0',
             'id': 1,
             'name': 'name_0',
             'phone': 'phone_0',
             'state_id': 1},
            {'address': 'address_1',
             'contact_person': 'contact_person_1',
             'email': 'email_1',
             'id': 2,
             'name': 'name_1',
             'phone': 'phone_1',
             'state_id': 2},
            {'address': 'address_2',
             'contact_person': 'contact_person_2',
             'email': 'email_2',
             'id': 3,
             'name': 'name_2',
             'phone': 'phone_2',
             'state_id': 3},
            {'address': 'address_3',
             'contact_person': 'contact_person_3',
             'email': 'email_3',
             'id': 4,
             'name': 'name_3',
             'phone': 'phone_3',
             'state_id': 4},
            {'address': 'address_4',
             'contact_person': 'contact_person_4',
             'email': 'email_4',
             'id': 5,
             'name': 'name_4',
             'phone': 'phone_4',
             'state_id': 5}]}
entities_data = sample_data

__meta__ = {'checksum': 'f48ce71835afd7ca38d00b7263ca8b3c484fdad0',
 'client': 'pioneer_wholesale_inc',
 'generated_at': '2025-08-16T15:52:46Z',
 'seed': 1337}
