entities_data = { 'cash_discount_group': { 'sample_data': [ { 'discount_percent': 5478.38,
                                              'id': 4747,
                                              'name': 'important',
                                              'terms': 'contain'},
                                            { 'discount_percent': 5602.62,
                                              'id': 2865,
                                              'name': 'a',
                                              'terms': 'care'},
                                            { 'discount_percent': 821.55,
                                              'id': 3070,
                                              'name': 'seem',
                                              'terms': 'through'},
                                            { 'discount_percent': 2347.69,
                                              'id': 9882,
                                              'name': 'same',
                                              'terms': 'prove'},
                                            { 'discount_percent': 5935.58,
                                              'id': 577,
                                              'name': 'also',
                                              'terms': 'group'}]},
  'customer': { 'sample_data': [ { 'address': 'figure',
                                   'credit_limit': 8066.23,
                                   'email': 'white',
                                   'id': 3506,
                                   'name': 'tree',
                                   'phone': 'such',
                                   'salesperson_id': 2125},
                                 { 'address': 'way',
                                   'credit_limit': 734.96,
                                   'email': 'surface',
                                   'id': 9100,
                                   'name': 'group',
                                   'phone': 'budget',
                                   'salesperson_id': 5013},
                                 { 'address': 'have',
                                   'credit_limit': 1409.71,
                                   'email': 'talk',
                                   'id': 7496,
                                   'name': 'care',
                                   'phone': 'child',
                                   'salesperson_id': 4647},
                                 { 'address': 'blue',
                                   'credit_limit': 8347.16,
                                   'email': 'finally',
                                   'id': 924,
                                   'name': 'call',
                                   'phone': 'car',
                                   'salesperson_id': 5758},
                                 { 'address': 'movement',
                                   'credit_limit': 114.15,
                                   'email': 'measure',
                                   'id': 4063,
                                   'name': 'grow',
                                   'phone': 'democratic',
                                   'salesperson_id': 727}]},
  'inventory': { 'sample_data': [ { 'id': 313,
                                    'item_id': 1610,
                                    'location_id': 6076,
                                    'quantity': 5379},
                                  { 'id': 8065,
                                    'item_id': 2452,
                                    'location_id': 9277,
                                    'quantity': 7887},
                                  { 'id': 3635,
                                    'item_id': 8795,
                                    'location_id': 8248,
                                    'quantity': 8345},
                                  { 'id': 2520,
                                    'item_id': 9326,
                                    'location_id': 7581,
                                    'quantity': 8701},
                                  { 'id': 9009,
                                    'item_id': 3483,
                                    'location_id': 4010,
                                    'quantity': 2455}]},
  'inventory_location': { 'sample_data': [ { 'address': 'fight',
                                             'id': 5313,
                                             'name': 'send'},
                                           { 'address': 'expect',
                                             'id': 2380,
                                             'name': 'stop'},
                                           { 'address': 'thousand',
                                             'id': 6512,
                                             'name': 'past'},
                                           { 'address': 'budget',
                                             'id': 5364,
                                             'name': 'social'},
                                           { 'address': 'box',
                                             'id': 1756,
                                             'name': 'enter'}]},
  'invoice': { 'sample_data': [ { 'customer_id': 3919,
                                  'date': '2025-04-05T10:46:03.390120',
                                  'id': 1883,
                                  'status': 'eat'},
                                { 'customer_id': 3577,
                                  'date': '2025-05-01T08:33:29.113025',
                                  'id': 5536,
                                  'status': 'no'},
                                { 'customer_id': 7308,
                                  'date': '2025-05-24T06:10:38.280398',
                                  'id': 9710,
                                  'status': 'treat'},
                                { 'customer_id': 3763,
                                  'date': '2025-06-25T14:55:45.067329',
                                  'id': 4928,
                                  'status': 'become'},
                                { 'customer_id': 3326,
                                  'date': '2025-05-13T15:32:57.519068',
                                  'id': 4771,
                                  'status': 'over'}]},
  'invoice_item': { 'sample_data': [ { 'invoice_id': 4740,
                                       'item_id': 764,
                                       'price': 981.69,
                                       'quantity': 2597},
                                     { 'invoice_id': 7885,
                                       'item_id': 7789,
                                       'price': 1756.01,
                                       'quantity': 6325},
                                     { 'invoice_id': 8797,
                                       'item_id': 8804,
                                       'price': 7522.97,
                                       'quantity': 2338},
                                     { 'invoice_id': 8158,
                                       'item_id': 5060,
                                       'price': 2514.2,
                                       'quantity': 6836},
                                     { 'invoice_id': 5073,
                                       'item_id': 3441,
                                       'price': 153.03,
                                       'quantity': 3776}]},
  'item': { 'sample_data': [ { 'active': True,
                               'cash_discount_group_id': 5344,
                               'category_id': 802,
                               'description': 'new',
                               'id': 5413,
                               'item_code': 'finally',
                               'name': 'machine',
                               'price': 3834.98,
                               'price_group_id': 733,
                               'secondary_category_id': 3813,
                               'tax_group_id': 4405,
                               'unit': 'suggest',
                               'upc_code': 'pattern',
                               'vendor_id': 3292},
                             { 'active': True,
                               'cash_discount_group_id': 6285,
                               'category_id': 8449,
                               'description': 'spend',
                               'id': 3017,
                               'item_code': 'should',
                               'name': 'enter',
                               'price': 2498.68,
                               'price_group_id': 9238,
                               'secondary_category_id': 7441,
                               'tax_group_id': 6357,
                               'unit': 'religious',
                               'upc_code': 'street',
                               'vendor_id': 3429},
                             { 'active': True,
                               'cash_discount_group_id': 5593,
                               'category_id': 5272,
                               'description': 'as',
                               'id': 1874,
                               'item_code': 'still',
                               'name': 'crime',
                               'price': 2863.61,
                               'price_group_id': 9753,
                               'secondary_category_id': 7150,
                               'tax_group_id': 2770,
                               'unit': 'guess',
                               'upc_code': 'oil',
                               'vendor_id': 1728},
                             { 'active': False,
                               'cash_discount_group_id': 8412,
                               'category_id': 2632,
                               'description': 'hospital',
                               'id': 5660,
                               'item_code': 'open',
                               'name': 'recent',
                               'price': 789.11,
                               'price_group_id': 5693,
                               'secondary_category_id': 7899,
                               'tax_group_id': 3304,
                               'unit': 'kid',
                               'upc_code': 'follow',
                               'vendor_id': 5835},
                             { 'active': True,
                               'cash_discount_group_id': 9755,
                               'category_id': 4151,
                               'description': 'cost',
                               'id': 6645,
                               'item_code': 'analysis',
                               'name': 'north',
                               'price': 3209.38,
                               'price_group_id': 4273,
                               'secondary_category_id': 3377,
                               'tax_group_id': 2369,
                               'unit': 'sure',
                               'upc_code': 'bring',
                               'vendor_id': 3357}]},
  'item_category': { 'sample_data': [ { 'description': 'skill',
                                        'id': 8100,
                                        'name': 'bed'},
                                      { 'description': 'late',
                                        'id': 8027,
                                        'name': 'send'},
                                      { 'description': 'anyone',
                                        'id': 8212,
                                        'name': 'population'},
                                      { 'description': 'executive',
                                        'id': 9131,
                                        'name': 'simply'},
                                      { 'description': 'clear',
                                        'id': 6971,
                                        'name': 'provide'}]},
  'price_group': { 'sample_data': [ { 'id': 4770,
                                      'markup_percent': 1513.34,
                                      'name': 'full'},
                                    { 'id': 5034,
                                      'markup_percent': 5653.3,
                                      'name': 'again'},
                                    { 'id': 8232,
                                      'markup_percent': 9500.44,
                                      'name': 'space'},
                                    { 'id': 9605,
                                      'markup_percent': 8268.94,
                                      'name': 'question'},
                                    { 'id': 2023,
                                      'markup_percent': 4319.93,
                                      'name': 'understand'}]},
  'purchase_order': { 'sample_data': [ { 'date': '2025-01-06T12:37:19.756205',
                                         'id': 3121,
                                         'status': 'describe',
                                         'vendor_id': 4114},
                                       { 'date': '2025-04-02T03:32:15.787115',
                                         'id': 4197,
                                         'status': 'range',
                                         'vendor_id': 9528},
                                       { 'date': '2025-04-25T08:40:37.096844',
                                         'id': 307,
                                         'status': 'student',
                                         'vendor_id': 5060},
                                       { 'date': '2025-05-08T16:50:36.757277',
                                         'id': 1461,
                                         'status': 'really',
                                         'vendor_id': 6716},
                                       { 'date': '2025-05-11T17:21:22.310085',
                                         'id': 1240,
                                         'status': 'consider',
                                         'vendor_id': 3969}]},
  'purchase_order_item': { 'sample_data': [ { 'item_id': 6310,
                                              'po_id': 8304,
                                              'quantity': 9479,
                                              'unit_price': 6226.32},
                                            { 'item_id': 4530,
                                              'po_id': 3775,
                                              'quantity': 2489,
                                              'unit_price': 9466.89},
                                            { 'item_id': 6523,
                                              'po_id': 8586,
                                              'quantity': 648,
                                              'unit_price': 5899.12},
                                            { 'item_id': 5261,
                                              'po_id': 8272,
                                              'quantity': 226,
                                              'unit_price': 9212.93},
                                            { 'item_id': 1953,
                                              'po_id': 634,
                                              'quantity': 4389,
                                              'unit_price': 5583.38}]},
  'salesperson': { 'sample_data': [ { 'email': 'type',
                                      'id': 9150,
                                      'name': 'drug',
                                      'phone': 'behavior'},
                                    { 'email': 'bar',
                                      'id': 1734,
                                      'name': 'clearly',
                                      'phone': 'safe'},
                                    { 'email': 'least',
                                      'id': 4312,
                                      'name': 'better',
                                      'phone': 'if'},
                                    { 'email': 'security',
                                      'id': 1438,
                                      'name': 'ability',
                                      'phone': 'available'},
                                    { 'email': 'raise',
                                      'id': 2028,
                                      'name': 'better',
                                      'phone': 'generation'}]},
  'secondary_category': { 'sample_data': [ { 'description': 'other',
                                             'id': 3288,
                                             'name': 'property'},
                                           { 'description': 'hot',
                                             'id': 402,
                                             'name': 'firm'},
                                           { 'description': 'because',
                                             'id': 8182,
                                             'name': 'girl'},
                                           { 'description': 'cell',
                                             'id': 5712,
                                             'name': 'artist'},
                                           { 'description': 'decade',
                                             'id': 2471,
                                             'name': 'support'}]},
  'tax_group': { 'sample_data': [ { 'id': 3319,
                                    'name': 'southern',
                                    'tax_percent': 701.95},
                                  { 'id': 646,
                                    'name': 'country',
                                    'tax_percent': 7501.0},
                                  { 'id': 8103,
                                    'name': 'food',
                                    'tax_percent': 170.41},
                                  { 'id': 9283,
                                    'name': 'value',
                                    'tax_percent': 9023.69},
                                  { 'id': 2526,
                                    'name': 'able',
                                    'tax_percent': 8375.47}]},
  'vendor': { 'sample_data': [ { 'address': 'structure',
                                 'contact_person': 'somebody',
                                 'email': 'relate',
                                 'id': 1361,
                                 'name': 'ago',
                                 'phone': 'follow'},
                               { 'address': 'term',
                                 'contact_person': 'ago',
                                 'email': 'lay',
                                 'id': 9261,
                                 'name': 'it',
                                 'phone': 'imagine'},
                               { 'address': 'apply',
                                 'contact_person': 'close',
                                 'email': 'great',
                                 'id': 2744,
                                 'name': 'bag',
                                 'phone': 'mouth'},
                               { 'address': 'career',
                                 'contact_person': 'represent',
                                 'email': 'have',
                                 'id': 409,
                                 'name': 'message',
                                 'phone': 'if'},
                               { 'address': 'worry',
                                 'contact_person': 'a',
                                 'email': 'me',
                                 'id': 8919,
                                 'name': 'push',
                                 'phone': 'throughout'}]}}